site_title = "MyArxiv"
limit_days = 7
cache_url = "https://katarinayuan.github.io/KGArxiv/cache.json"

[[sources]]
limit = 150
category = "cs.CL"
title = "Computation and Language"

[[sources]]
limit = 150
category = "cs.KG"
title = "Knowledge Graph"

[[sources]]
limit = 150
category = "cs.Induc"
title = "Inductive"

[[sources]]
limit = 150
category = "cs.Induc"
title = "Transfer"

[[sources]]
limit = 150
category = "cs.GNN"
title = "Graph Neural Network"

[[sources]]
limit = 150
category = "cs.RL"
title = "Representation Learning"

[scripts]
highlight_title = "scripts/highlight_title.rhai"
highlight_author = "scripts/highlight_author.rhai"
highlight_conference = "scripts/highlight_conference.rhai"
